[tools]
go = "latest"
java = "21"
maven = "latest"
node = "latest"
python = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
pipx = "latest"
ansible = "latest"
azure-functions-core-tools = "latest"
"npm:typescript-language-server" = "latest"
